### ISSUE TITLE
Kafka plugin install won't accept --bro-dist path

### ISSUE THREAD

**Issue by vesche** [bro/bro-plugins#28] opened 2016-06-02 01:14 UTC
I'm trying to compile the kafka plugin, but I'm having an issue with it accepting the `--bro-dist` argument. I have bro installed and working under `/opt/bro`. This is the error I'm getting:
```
# ./configure --bro-dist=/opt/bro
Cannot determine Bro source directory, use --bro-dist=DIR.
```
Is it wanting a path to the bro source code? I hope I can avoid re-building bro from source to add this plugin.

**Comment by MythRen** [comment] 2016-06-02 03:29
--bro-dist should be the path that store the bro source code .   
you don't need re-building bro from source after install Kafka plugin

**Comment by 0xxon** [comment] 2016-06-02 23:07
Just to confirm what @MythRen said - bro-dist needs to point at the bro source code.

While you potentially do not have to re-build Bro from source (assuming that the source code matches the installed version), I would recommend it. You will have to at least run ./configure with the correct options and then you are already nearly here.

In any case, I will close this since it is not a bug. For further support on this, our mailing list (http://mailman.icsi.berkeley.edu/mailman/listinfo/bro), IRC or Gitter channels are the better venue.

**Closed by 0xxon** 2016-06-02 23:07 UTC
