### ISSUE TITLE
Plugin Bro::Netmap working but another applications can't transmit data.

### ISSUE THREAD

**Issue by nguyenductin113** [bro/bro-plugins#47] opened 2017-06-22 09:41 UTC
I just got plugin Bro::Netmap working on CentOS 7 and FreeBSD 11, Bro is now able to receives packets and filters them using `bro -i netmap::em0 script_file` .  
But the problem is I can't use that interface with non-netmap applications which is meaningless as a traffic monitor.
So i guest Bro is not correct in forwarding packets to application land. 
Does anyone ever have this issue before ?

**Comment by 0xxon** [comment] 2017-06-23 19:30
Hi,

if I understand everything correctly, Bro is able to read data using netmap. The fact that you will not be able to use non-netmap applications simultaneously has nothing to do with Bro and is, as far as I am aware, by design. Processing is supposed to sidestep the kernel, so non-netmap applications will not see the traffic.

As this is not a bug I am going to close this.

If you have any questions about this, please use the main bro mailing list bro@bro.org; you will reach more people with experience with using netmap.

**Closed by 0xxon** 2017-06-23 19:30 UTC

**Comment by sethhall** [comment] 2017-06-24 12:43
You need to use the "lb" utility that ships with netmap in order to balance
traffic out to multiple processes. It's also possible to use special flags
to replicate the traffic internally in netmap.  I will post some
documentation for how to do all of this in a few weeks.

  .Seth

**Comment by nguyenductin113** [comment] 2017-06-24 14:59
Thank you for helping me figure out the problem, can't wait to see the good news.
